CREATE SCHEMA IF NOT EXISTS sm_auth;
CREATE SCHEMA IF NOT EXISTS sm_dictionary;
CREATE SCHEMA IF NOT EXISTS sm_food;
CREATE SCHEMA IF NOT EXISTS sm_menu;
CREATE SCHEMA IF NOT EXISTS sm_profile;
CREATE SCHEMA IF NOT EXISTS sm_analytic;
